### ISSUE TITLE
rethink prefix command line flags?

### ISSUE THREAD

**Issue by rogpeppe** [awalterschulze/goderive#28]
To my mind having a separate flag for every individual derived function makes
the command line interface somewhat cluttered. I wonder if it might be cleaner
with something like:

    -prefix string
        set the prefix for derived function names (default "derive")
    -pluginprefix string
        set the prefix for a particular derived function, in the form plugin=prefix.
        For example, to change the name of the derived copy function to Copy
        instead of the default deriveCopy, use -pluginprefix copy=Copy

Then the number of command line flags won't need to be proportional to the
number of plugins, and it's easy to change the prefix for all of them at once
(for example to use "generate*" rather than "derive*").

**Comment by awalterschulze** [comment]
I like the idea of the single prefix flag to for example change `derive` to `generate` on all plugins.

But I don't see a problem with the amount of command line flags.  Maybe you can explain why you think a high number of command line flags is a bad idea?

**Comment by rogpeppe** [comment]
It means that it's hard to see the wood for the trees when doing goderive -help.
For example, the -dedup and -autoname flags are buried in the middle of
all the other prefix flags and are hard to find. As the number of plugins grows,
as it surely will, this will only get worse. I think it's nicer to expose the underlying
regularity by providing a more general flag that is used the same for any plugin.

**Comment by awalterschulze** [comment]
ok thats a good point.  I am sold.

**Comment by awalterschulze** [comment]
Done

https://github.com/awalterschulze/goderive/commit/9bfc0ebabc5e44ba8ac9dc24065c4c18d6e76ee9
