### ISSUE TITLE
Function names when deriving for multiple types are not descriptive

### ISSUE THREAD

**Issue by twpayne** [awalterschulze/goderive#33]
I am interested in using `goderive` for https://github.com/twpayne/go-geom which exports multiple distinct types.

Some packages may wish to derive functions for multiple types, for example:

```go
package main

type MyFirstStruct struct {
	Int64 int64
}

func (this *MyFirstStruct) Equal(that *MyFirstStruct) bool {
	return deriveEqual(this, that)
}

type MySecondStruct struct {
	StringPtr *string
}

func (this *MySecondStruct) Equal(that *MySecondStruct) bool {
	return deriveEqual(this, that)
}
```

In this case, there is an obvious conflict: `deriveEqual` cannot be overloaded to support both types.

Running `goderive -autoname` resolves this conflict:

```
$ goderive -autoname .
changing function call name from deriveEqual to deriveEqual_
```

The function names `derivedEqual` and `derivedEqual_` are not particularly descriptive and easily misread or mis-typed. Instead they should include the name of the type, e.g. `deriveEqual_MyFirstStruct` and `deriveEqual_MySecondStruct`.

**Comment by s-kostyaev** [comment]
I think this can be useful for many derives, not only `deriveEqual`.

**Comment by awalterschulze** [comment]
goderive simply needs to see a prefix to know that the function needs to be
generated. You can add any descriptive suffix and it will still work.

And if you don't run it with -dedup you will get an error if you mistype it
and call it with the same input types.

I hope that helps?
Sorry for the delayed response.

**Comment by awalterschulze** [comment]
If you would like to add your project to the users list, please make a pull request :)

That is if I answered your question?

**Comment by twpayne** [comment]
Thanks! That answers my question - I missed that you could derive multiple functions by using different suffixes. I'll submit a PR to make this more explicit in the `README.md` and a PR for projects using `goderive` when I get it working.

**Comment by awalterschulze** [comment]
Awesome 😀 that will be much appreciated
