### ISSUE TITLE
support multiple GOPATH's

### ISSUE THREAD

**Issue by dvic** [awalterschulze/goderive#36]
Please correct me if I'm wrong but shouldn't [this](https://github.com/awalterschulze/goderive/blob/86b0a3fcf424310744df60c69cdfb31c0a8e21be/derive/generate.go#L209) line should split on `:` and try each GOPATH (in order)?

**Comment by awalterschulze** [comment]
My bad.  I forgot people used multiple gopaths.
Here is the fix
https://github.com/awalterschulze/goderive/commit/01fa5ea67325abaa32922c61e1c4fd154133e136

**Comment by awalterschulze** [comment]
Thanks for reporting :)
