### ISSUE TITLE
Missing support for embedded non-trivial types

### ISSUE THREAD

**Issue by twpayne** [awalterschulze/goderive#38]
Consider the following, where an un-exported non-trivial type (containing an `[]int`) is embedded in an exported type:

```go
package embed_unexported

type unexported struct {
	private []int
}

type Exported struct {
	unexported
}

func (e *Exported) Clone() *Exported {
	newExported := &Exported{}
	deriveDeepCopyExported(newExported, e)
	return newExported
}
```

I would expect `goderive` to be able to derive `deriveDeepCopyExported`, but instead it emits the error message:

```
Generator Error: deepcopy:unsupported deepcopy type: unexported
```

`goderive` is able derive `DeepCopy` for `unexported` so it is surprising that it emits an error message for an exported type containing an embedded `unexported`.

For reference, when fed

```go
func (u *unexported) clone() *unexported {
	newUnexported := &unexported{}
	deriveDeepCopyUnexported(newUnexported, u)
	return newUnexported
}
```

`goderive` generates

```go
// Code generated by goderive DO NOT EDIT.

package embed_unexported

// deriveDeepCopyUnexported recursively copies the contents of src into dst.
func deriveDeepCopyUnexported(dst, src *unexported) {
	if src.private == nil {
		dst.private = nil
	} else {
		if dst.private != nil {
			if len(src.private) > len(dst.private) {
				if cap(dst.private) >= len(src.private) {
					dst.private = (dst.private)[:len(src.private)]
				} else {
					dst.private = make([]int, len(src.private))
				}
			} else if len(src.private) < len(dst.private) {
				dst.private = (dst.private)[:len(src.private)]
			}
		} else {
			dst.private = make([]int, len(src.private))
		}
		copy(dst.private, src.private)
	}
}
```

`goderive` also works when `unexported` only contains a trivial type (e.g. if you change the type of `private` from `[]int` to `int`).

Is it possible for `goderive` to derive functions for `struct`s containing un-exported non-trivial types?

**Comment by awalterschulze** [comment]
This sounds solvable as long as unexported is in the same package.
I think this is a shortcut I took just for deepcopy.
I am going to a conference for the week, but I will fix this when I get
back.

Thanks for reporting.

**Comment by awalterschulze** [comment]
fixed
https://github.com/awalterschulze/goderive/commit/f79860d57ae81d6ccd794120e5f29acd105861c1

**Comment by twpayne** [comment]
Thank you :)
