### ISSUE TITLE
deriveEqual: Use Equal() if it is defined on T

### ISSUE THREAD

**Issue by gpaul** [awalterschulze/goderive#44]
I would like to generate `deriveEqual` for the following type hierarchy:

```
type Foo struct {
    Field Bar
}

func (this *Foo) Equal(that *Foo) bool {
    return deriveEqual(this, that)
}

type Bar map[string]interface{}
```

Now, as it is not possible to derive an `Equal` for an `interface{}` this fails. However, I would like to implement `func (Bar) Equal(other Bar) bool {}` myself and have `deriveEqual` notice that and call it instead.

That way I can take responsibility for the fact that I end up calling `reflect.DeepEqual()` or implementing custom `Equal` logic lower down my type hierarchy while still benefiting from all the lovely code generation for the rest of it.

**Comment by awalterschulze** [comment]
goderive does some check for equal methods on structs, but maybe goderive could do more :)
I'll look into making sure this works.

**Comment by awalterschulze** [comment]
Should work now
https://github.com/awalterschulze/goderive/commit/77a50e43e09d55ef12d439668ef3712369272bde

**Comment by gpaul** [comment]
Wow that was fast, thank you! Works like a charm.

**Comment by awalterschulze** [comment]
My pleasure :)  It was an easy fix.

If you are using it in some project, we would love to add that project to your users list, if possible?

**Comment by gpaul** [comment]
Sigh for the moment it is closed source, sorry. We plan on open sourcing part of it in the next few months though.

**Comment by awalterschulze** [comment]
No problem.  Just trying my luck :)

**Comment by gpaul** [comment]
If you're happy with just "used by XXX" then I'll let you know once we release the closed source version, right now the project is in early development.

**Comment by awalterschulze** [comment]
Also happy to add used by XXX with a link to the closed source project.

**Comment by sakeven** [comment]
@awalterschulze Hi, I think we should use Equal() before using “==” if Equal is defined for T. This is because if T changes, we can’t use “==” and it may only be equal through Equal().
