### ISSUE TITLE
Doc: Explain how to contribute a new plugin

### ISSUE THREAD

**Issue by awalterschulze** [awalterschulze/goderive#45]

**Comment by awalterschulze** [comment]
I have updated
https://github.com/awalterschulze/goderive/blob/master/Contributing.md
Maybe it needs more work, but I think it is a start.

**Comment by awalterschulze** [comment]
@ingun37 If you have time it would be great if you can check the updated version for errors and maybe update it with anything that would have helped you?

**Comment by ingun37** [comment]
@awalterschulze 
Maybe the functions in `goderive/derive/types.go`?
It was happy accident to find the functions. It saved some lines.

**Comment by awalterschulze** [comment]
I tried adding another section
https://github.com/awalterschulze/goderive/blob/master/Contributing.md#dont-repeat-yourself
What do you think?
