### ISSUE TITLE
deriveEqual: Use Equal() instead of '==' if it is defined on T, even if the type canEqual

### ISSUE THREAD

**Issue by sakeven** [awalterschulze/goderive#82]
If someone has defined the Equal() method on types which canEqual, they likely intend to use Equal() method instead of '==' when comparing two values.
<img width="392" alt="image" src="https://user-images.githubusercontent.com/4099405/230526638-06f5d775-b677-481e-bf5c-52135aa88507.png">

**Comment by awalterschulze** [comment]
Fair, do you want to give this a go?

**Comment by sakeven** [comment]
Yes, I would be happy to.
